language: elixir
elixir:
- 1.0.5
otp_release:
- 18.0
script:
- ./test.sh
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database nova_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
